// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LocationRotation.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "LocationRotation.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define LocationRotationBean_max_cdr_typesize 260ULL;
#define LocationRotationBean_max_key_cdr_typesize 0ULL;

LocationRotationBean::LocationRotationBean()
{
    // string m_LRJsonString
    m_LRJsonString ="";

}

LocationRotationBean::~LocationRotationBean()
{
}

LocationRotationBean::LocationRotationBean(
        const LocationRotationBean& x)
{
    m_LRJsonString = x.m_LRJsonString;
}

LocationRotationBean::LocationRotationBean(
        LocationRotationBean&& x) noexcept 
{
    m_LRJsonString = std::move(x.m_LRJsonString);
}

LocationRotationBean& LocationRotationBean::operator =(
        const LocationRotationBean& x)
{

    m_LRJsonString = x.m_LRJsonString;

    return *this;
}

LocationRotationBean& LocationRotationBean::operator =(
        LocationRotationBean&& x) noexcept
{

    m_LRJsonString = std::move(x.m_LRJsonString);

    return *this;
}

bool LocationRotationBean::operator ==(
        const LocationRotationBean& x) const
{

    return (m_LRJsonString == x.m_LRJsonString);
}

bool LocationRotationBean::operator !=(
        const LocationRotationBean& x) const
{
    return !(*this == x);
}

size_t LocationRotationBean::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return LocationRotationBean_max_cdr_typesize;
}

size_t LocationRotationBean::getCdrSerializedSize(
        const LocationRotationBean& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.LRJsonString().size() + 1;

    return current_alignment - initial_alignment;
}

void LocationRotationBean::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_LRJsonString.c_str();

}

void LocationRotationBean::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_LRJsonString;}

/*!
 * @brief This function copies the value in member LRJsonString
 * @param _LRJsonString New value to be copied in member LRJsonString
 */
void LocationRotationBean::LRJsonString(
        const std::string& _LRJsonString)
{
    m_LRJsonString = _LRJsonString;
}

/*!
 * @brief This function moves the value in member LRJsonString
 * @param _LRJsonString New value to be moved in member LRJsonString
 */
void LocationRotationBean::LRJsonString(
        std::string&& _LRJsonString)
{
    m_LRJsonString = std::move(_LRJsonString);
}

/*!
 * @brief This function returns a constant reference to member LRJsonString
 * @return Constant reference to member LRJsonString
 */
const std::string& LocationRotationBean::LRJsonString() const
{
    return m_LRJsonString;
}

/*!
 * @brief This function returns a reference to member LRJsonString
 * @return Reference to member LRJsonString
 */
std::string& LocationRotationBean::LRJsonString()
{
    return m_LRJsonString;
}


size_t LocationRotationBean::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return LocationRotationBean_max_key_cdr_typesize;
}

bool LocationRotationBean::isKeyDefined()
{
    return false;
}

void LocationRotationBean::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}
